export const CountryList = [
  { country: "Nigeria", countryCode: "1" },
  // { country: "Ghana", countryCode: "2" },
  // { country: "Senegal", countryCode: "3" },
];

export const StateList = [
  { country: "Abia", stateCode: "1" },
  { country: "Adamawa", stateCode: "2" },
  { country: "Akwa Ibom", stateCode: "3" },
  { country: "Anambra", stateCode: "4" },
  { country: "Bauchi", stateCode: "5" },
  { country: "Bayelsa", stateCode: "6" },
  { country: "Benue", stateCode: "7" },
  { country: "Borno", stateCode: "8" },
  { country: "Cross River", stateCode: "9" },
  { country: "Delta", stateCode: "10" },
  { country: "Ebonyi", stateCode: "11" },
  { country: "Edo", stateCode: "12" },
  { country: "Ekiti", stateCode: "13" },
  { country: "Enugu", stateCode: "14" },
  { country: "Gombe", stateCode: "15" },
  { country: "Imo", stateCode: "16" },
  { country: "Jigawa", stateCode: "17" },
  { country: "Kaduna", stateCode: "18" },
  { country: "Kano", stateCode: "19" },
  { country: "Katsina", stateCode: "20" },
  { country: "Kebbi", stateCode: "21" },
  { country: "Kogi", stateCode: "22" },
  { country: "Kwara", stateCode: "23" },
  { country: "Lagos", stateCode: "24" },
  { country: "Nasarawa", stateCode: "25" },
  { country: "Niger", stateCode: "26" },
  { country: "Ogun", stateCode: "27" },
  { country: "Ondo", stateCode: "28" },
  { country: "Osun", stateCode: "29" },
  { country: "Oyo", stateCode: "30" },
  { country: "Plateau", stateCode: "31" },
  { country: "Rivers", stateCode: "32" },
  { country: "Sokoto", stateCode: "33" },
  { country: "Taraba", stateCode: "34" },
  { country: "Yobe", stateCode: "35" },
  { country: "Zamfara", stateCode: "36" },
  { country: "Abuja", stateCode: "37" },
];

export const OccupationList = [
  "Medical Doctor",
  "Nurse",
  "Midwife",
  "Nurse and Midwife",
  "Pharmacist",
  "Medical laboratory scientist",
  "Occupational therapist",
  "Speech therapist",
  "Osteopathic medicine",
  "Prosthetics and orthotics",
  "Physiotherapist",
  "Chiropractor",
  "Health Technician",
];

export const Experience = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
